# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build package

on:
  push:
    branches: [ magistra ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install package
      run: npm ci
    - name: Install package
      run: npm run build-production
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: kagimori.zip
        path: dist/** icons/** static/** manifest.json
