name: Run unit tests

on:
  push:
    branches-ignore:
      - dependabot/**
    tags:
      - v*
  pull_request:
    branches:
      - magistra

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Install package
      run: npm ci
    - name: Create a package
      run: npm run test
